#!/usr/bin/env bash
set -e

# SagensContact Installer
# Automated installation script for testers
# Supports both fresh installations and upgrades from previous versions

BOLD='\033[1m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Version tracking
INSTALLER_VERSION="0.1.0-alpha.3"
VERSION_FILE=".sagenscontact_version"

echo -e "${BOLD}╔═══════════════════════════════════════╗${NC}"
echo -e "${BOLD}║   SagensContact Alpha Installer      ║${NC}"
echo -e "${BOLD}║   Version: $INSTALLER_VERSION              ║${NC}"
echo -e "${BOLD}╚═══════════════════════════════════════╝${NC}"
echo ""

# Check if running from correct directory
if [ ! -f "Cargo.toml" ] || [ ! -d "crates" ]; then
    echo -e "${RED}Error: Please run this script from the sagenscontact/alpha directory${NC}"
    echo "Usage: cd alpha && ./install.sh"
    exit 1
fi

# Check for existing installation
EXISTING_INSTALL=false
UPGRADE_MODE=false

if [ -f "$VERSION_FILE" ]; then
    EXISTING_INSTALL=true
    OLD_VERSION=$(head -1 "$VERSION_FILE")
    echo -e "${BLUE}Existing installation detected: v$OLD_VERSION${NC}"

    if [ "$OLD_VERSION" = "$INSTALLER_VERSION" ]; then
        echo -e "${YELLOW}Same version already installed. Reinstalling...${NC}"
    else
        echo -e "${GREEN}Upgrading from v$OLD_VERSION to v$INSTALLER_VERSION${NC}"
    fi
    UPGRADE_MODE=true
    echo ""
elif [ -f "target/release/sagenscontact" ] || [ -f "target/release/sync_service" ]; then
    EXISTING_INSTALL=true
    echo -e "${YELLOW}Existing build found (unknown version). Upgrading...${NC}"
    UPGRADE_MODE=true
    echo ""
fi

# Create pre-upgrade backup if upgrading
if [ "$UPGRADE_MODE" = true ]; then
    echo -e "${BOLD}Creating pre-upgrade backup...${NC}"

    BACKUP_DIR="data/backups"
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    mkdir -p "$BACKUP_DIR"

    # Backup database and config
    if [ -f "data/contacts.db" ] || [ -f ".env" ]; then
        tar -czf "$BACKUP_DIR/pre-upgrade-$TIMESTAMP.tar.gz" \
            data/contacts.db \
            data/attachments/ \
            .env \
            "$VERSION_FILE" 2>/dev/null || true
        echo -e "${GREEN}✓ Backup created: $BACKUP_DIR/pre-upgrade-$TIMESTAMP.tar.gz${NC}"

        # Keep only last 5 pre-upgrade backups
        cd "$BACKUP_DIR"
        ls -t pre-upgrade-*.tar.gz 2>/dev/null | tail -n +6 | xargs rm -f 2>/dev/null || true
        cd - > /dev/null
    fi

    # Stop existing services
    echo -e "${BOLD}Stopping existing services...${NC}"
    ./stop.sh 2>/dev/null || true
    sleep 2
    echo ""
fi

# Detect OS
OS="$(uname -s)"
case "${OS}" in
    Linux*)     MACHINE=Linux;;
    Darwin*)    MACHINE=Mac;;
    *)          MACHINE="UNKNOWN:${OS}"
esac

echo -e "${GREEN}✓ Detected OS: ${MACHINE}${NC}"
echo ""

# Check Prerequisites
echo -e "${BOLD}Checking prerequisites...${NC}"

# Check Rust
if command -v rustc &> /dev/null; then
    RUST_VERSION=$(rustc --version | awk '{print $2}')
    echo -e "${GREEN}✓ Rust installed: ${RUST_VERSION}${NC}"
else
    echo -e "${YELLOW}! Rust not found. Installing...${NC}"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source $HOME/.cargo/env
    echo -e "${GREEN}✓ Rust installed${NC}"
fi

# Check Cargo
if ! command -v cargo &> /dev/null; then
    echo -e "${RED}✗ Cargo not found after Rust installation${NC}"
    exit 1
fi

# Install system dependencies
echo ""
echo -e "${BOLD}Installing system dependencies...${NC}"

if [ "$MACHINE" = "Mac" ]; then
    if command -v brew &> /dev/null; then
        brew install sqlite pkg-config openssl
        echo -e "${GREEN}✓ System dependencies installed${NC}"
    else
        echo -e "${YELLOW}! Homebrew not found. Please install: https://brew.sh${NC}"
        echo "Then run: brew install sqlite pkg-config openssl"
    fi
elif [ "$MACHINE" = "Linux" ]; then
    if command -v apt-get &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev pkg-config libssl-dev build-essential
        echo -e "${GREEN}✓ System dependencies installed${NC}"
    else
        echo -e "${YELLOW}! Please install: libsqlite3-dev pkg-config libssl-dev${NC}"
    fi
fi

# Build the project
echo ""
echo -e "${BOLD}Building SagensContact (this may take 5-10 minutes)...${NC}"
cargo build --release

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ Build successful!${NC}"
else
    echo -e "${RED}✗ Build failed. Please check the error messages above.${NC}"
    exit 1
fi

# Create data directory
echo ""
echo -e "${BOLD}Setting up data directory...${NC}"
mkdir -p data/attachments
mkdir -p data/backups
echo -e "${GREEN}✓ Data directories created${NC}"

# Generate default environment file
echo ""
echo -e "${BOLD}Creating default configuration...${NC}"

cat > .env << 'EOF'
# SagensContact Environment Configuration
# Generated by installer

# Database
DATABASE_URL=sqlite:data/contacts.db

# Server
PORT=3000

# Security (CHANGE THESE IN PRODUCTION!)
JWT_SECRET=change-me-to-a-secure-random-32-character-minimum-secret-key-for-production

# Twilio SMS (Optional - leave empty to use mock adapter)
# TWILIO_ACCOUNT_SID=
# TWILIO_AUTH_TOKEN=
# TWILIO_PHONE_NUMBER=

# Worker Secret (for internal communication)
WORKER_SECRET=change-me-to-another-secure-32-character-minimum-secret-key-please

# Logging
RUST_LOG=info
EOF

echo -e "${GREEN}✓ Configuration file created: .env${NC}"
echo -e "${YELLOW}⚠ WARNING: Please update JWT_SECRET and WORKER_SECRET in .env before production use!${NC}"

# Create convenience scripts
echo ""
echo -e "${BOLD}Creating convenience scripts...${NC}"

cat > start.sh << 'EOF'
#!/usr/bin/env bash
# Load environment variables
set -a
source .env 2>/dev/null || true
set +a

echo "Starting SagensContact services..."

# Start sync service
DATABASE_URL="${DATABASE_URL:-sqlite:data/contacts.db}" \
JWT_SECRET="${JWT_SECRET}" \
WORKER_SECRET="${WORKER_SECRET}" \
PORT="${PORT:-3000}" \
RUST_LOG="${RUST_LOG:-info}" \
./target/release/sync_service > logs/sync_service.log 2>&1 &
SYNC_PID=$!
echo "✓ Sync service started (PID: $SYNC_PID)"

# Start worker
sleep 2
DATABASE_URL="${DATABASE_URL:-sqlite:data/contacts.db}" \
WORKER_SECRET="${WORKER_SECRET}" \
RUST_LOG="${RUST_LOG:-info}" \
./target/release/worker > logs/worker.log 2>&1 &
WORKER_PID=$!
echo "✓ Worker started (PID: $WORKER_PID)"

echo ""
echo "SagensContact is running!"
echo "  - API: http://localhost:${PORT:-3000}"
echo "  - Health: http://localhost:${PORT:-3000}/health"
echo ""
echo "View logs:"
echo "  tail -f logs/sync_service.log"
echo "  tail -f logs/worker.log"
echo ""
echo "Stop with: ./stop.sh"
EOF

cat > stop.sh << 'EOF'
#!/usr/bin/env bash
echo "Stopping SagensContact services..."

pkill -f "sync_service" && echo "✓ Sync service stopped"
pkill -f "worker" && echo "✓ Worker stopped"

echo "All services stopped."
EOF

cat > backup.sh << 'EOF'
#!/usr/bin/env bash
set -e

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="data/backups"
DATABASE="${DATABASE_URL:-sqlite:data/contacts.db}"
DB_FILE="${DATABASE#sqlite:}"

mkdir -p "$BACKUP_DIR"

echo "Creating backup: $BACKUP_DIR/backup_$TIMESTAMP.tar.gz"

# Backup database and attachments
tar -czf "$BACKUP_DIR/backup_$TIMESTAMP.tar.gz" \
    "$DB_FILE" \
    data/attachments/ \
    .env 2>/dev/null || true

echo "✓ Backup created successfully!"
echo "  Location: $BACKUP_DIR/backup_$TIMESTAMP.tar.gz"
echo "  Size: $(du -h "$BACKUP_DIR/backup_$TIMESTAMP.tar.gz" | cut -f1)"

# Keep only last 10 backups
cd "$BACKUP_DIR"
ls -t backup_*.tar.gz | tail -n +11 | xargs rm -f 2>/dev/null || true
echo "✓ Old backups cleaned (keeping last 10)"
EOF

cat > restore.sh << 'EOF'
#!/usr/bin/env bash
set -e

if [ -z "$1" ]; then
    echo "Usage: ./restore.sh <backup_file>"
    echo ""
    echo "Available backups:"
    ls -lh data/backups/backup_*.tar.gz 2>/dev/null || echo "  No backups found"
    exit 1
fi

BACKUP_FILE="$1"

if [ ! -f "$BACKUP_FILE" ]; then
    echo "Error: Backup file not found: $BACKUP_FILE"
    exit 1
fi

echo "⚠ WARNING: This will overwrite your current data!"
read -p "Continue? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "Restore cancelled."
    exit 0
fi

echo "Stopping services..."
./stop.sh 2>/dev/null || true
sleep 2

echo "Restoring from: $BACKUP_FILE"
tar -xzf "$BACKUP_FILE"

echo "✓ Restore complete!"
echo "Start services with: ./start.sh"
EOF

chmod +x start.sh stop.sh backup.sh restore.sh
mkdir -p logs

echo -e "${GREEN}✓ Scripts created: start.sh, stop.sh, backup.sh, restore.sh${NC}"

# Write version file
cat > "$VERSION_FILE" << EOF
$INSTALLER_VERSION
Installed: $(date -Iseconds)
Installer: install.sh
EOF
echo -e "${GREEN}✓ Version file created${NC}"

# Installation/Upgrade complete
echo ""
if [ "$UPGRADE_MODE" = true ]; then
    echo -e "${BOLD}${GREEN}╔═══════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${GREEN}║   Upgrade Complete! 🎉                ║${NC}"
    echo -e "${BOLD}${GREEN}╚═══════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${GREEN}Upgraded to version $INSTALLER_VERSION${NC}"
    echo -e "Your data and configuration have been preserved."
    echo -e "Pre-upgrade backup: data/backups/pre-upgrade-*.tar.gz"
else
    echo -e "${BOLD}${GREEN}╔═══════════════════════════════════════╗${NC}"
    echo -e "${BOLD}${GREEN}║   Installation Complete! 🎉           ║${NC}"
    echo -e "${BOLD}${GREEN}╚═══════════════════════════════════════╝${NC}"
fi
echo ""
echo -e "${BOLD}Quick Start:${NC}"
echo ""
echo -e "  1. Start services:    ${GREEN}./start.sh${NC}"
echo -e "  2. Test API:          ${GREEN}curl http://localhost:3000/health${NC}"
echo -e "  3. Create backup:     ${GREEN}./backup.sh${NC}"
echo -e "  4. Stop services:     ${GREEN}./stop.sh${NC}"
echo ""
echo -e "${BOLD}Testing:${NC}"
echo -e "  CLI:                  ${GREEN}./target/release/sagenscontact --help${NC}"
echo -e "  Create contact:       ${GREEN}./target/release/sagenscontact create${NC}"
echo -e "  List contacts:        ${GREEN}./target/release/sagenscontact list${NC}"
echo ""
echo -e "${BOLD}Documentation:${NC}"
echo -e "  Quick Start:          ${GREEN}cat QUICKSTART.md${NC}"
echo -e "  Twilio SMS Setup:     ${GREEN}cat TWILIO_SMS_SETUP.md${NC}"
echo -e "  Architecture:         ${GREEN}cat ARCHITECTURE.md${NC}"
echo ""
echo -e "${YELLOW}⚠ Security Note:${NC} Update JWT_SECRET and WORKER_SECRET in .env before production!"
echo ""
