import { c as create_ssr_component } from "../../../chunks/ssr.js";
import "../../../chunks/api.js";
const css = {
  code: ".page.svelte-12ipolu{padding:2rem;max-width:800px}.header.svelte-12ipolu{display:flex;justify-content:space-between;margin-bottom:2rem}.history-list.svelte-12ipolu{display:flex;flex-direction:column;gap:0.5rem}.history-item.svelte-12ipolu{padding:1rem}.query.svelte-12ipolu{font-weight:600;margin-bottom:0.5rem}.meta.svelte-12ipolu{font-size:0.875rem;color:var(--gray-600);display:flex;gap:1rem}.empty.svelte-12ipolu{text-align:center;padding:3rem}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script lang=\\"ts\\">import { onMount } from \\"svelte\\";\\nimport { api } from \\"$lib/api/api\\";\\nlet history = [];\\nlet loading = true;\\nonMount(async () => {\\n  await loadHistory();\\n});\\nasync function loadHistory() {\\n  try {\\n    history = await api.getSearchHistory();\\n  } catch (error) {\\n    console.error(\\"Failed to load history:\\", error);\\n  } finally {\\n    loading = false;\\n  }\\n}\\nasync function handleClear() {\\n  if (!confirm(\\"Clear all search history?\\")) return;\\n  try {\\n    await api.clearSearchHistory();\\n    history = [];\\n  } catch (error) {\\n    alert(\\"Failed: \\" + error.message);\\n  }\\n}\\n<\/script>\\n\\n<div class=\\"page\\">\\n\\t<div class=\\"header\\">\\n\\t\\t<h1>Search History</h1>\\n\\t\\t{#if history.length > 0}\\n\\t\\t\\t<button on:click={handleClear} class=\\"btn btn-secondary\\">Clear History</button>\\n\\t\\t{/if}\\n\\t</div>\\n\\n\\t{#if loading}\\n\\t\\t<div>Loading...</div>\\n\\t{:else if history.length === 0}\\n\\t\\t<div class=\\"empty\\">No search history</div>\\n\\t{:else}\\n\\t\\t<div class=\\"history-list\\">\\n\\t\\t\\t{#each history as item}\\n\\t\\t\\t\\t<div class=\\"history-item card\\">\\n\\t\\t\\t\\t\\t<div class=\\"query\\">\\"{item.query}\\"</div>\\n\\t\\t\\t\\t\\t<div class=\\"meta\\">\\n\\t\\t\\t\\t\\t\\t<span>{item.result_count} results</span>\\n\\t\\t\\t\\t\\t\\t<span>{new Date(item.created_at).toLocaleString()}</span>\\n\\t\\t\\t\\t\\t</div>\\n\\t\\t\\t\\t</div>\\n\\t\\t\\t{/each}\\n\\t\\t</div>\\n\\t{/if}\\n</div>\\n\\n<style>\\n\\t.page { padding: 2rem; max-width: 800px; }\\n\\t.header { display: flex; justify-content: space-between; margin-bottom: 2rem; }\\n\\t.history-list { display: flex; flex-direction: column; gap: 0.5rem; }\\n\\t.history-item { padding: 1rem; }\\n\\t.query { font-weight: 600; margin-bottom: 0.5rem; }\\n\\t.meta { font-size: 0.875rem; color: var(--gray-600); display: flex; gap: 1rem; }\\n\\t.empty { text-align: center; padding: 3rem; }\\n</style>\\n"],"names":[],"mappings":"AAuDC,oBAAM,CAAE,OAAO,CAAE,IAAI,CAAE,SAAS,CAAE,KAAO,CACzC,sBAAQ,CAAE,OAAO,CAAE,IAAI,CAAE,eAAe,CAAE,aAAa,CAAE,aAAa,CAAE,IAAM,CAC9E,4BAAc,CAAE,OAAO,CAAE,IAAI,CAAE,cAAc,CAAE,MAAM,CAAE,GAAG,CAAE,MAAQ,CACpE,4BAAc,CAAE,OAAO,CAAE,IAAM,CAC/B,qBAAO,CAAE,WAAW,CAAE,GAAG,CAAE,aAAa,CAAE,MAAQ,CAClD,oBAAM,CAAE,SAAS,CAAE,QAAQ,CAAE,KAAK,CAAE,IAAI,UAAU,CAAC,CAAE,OAAO,CAAE,IAAI,CAAE,GAAG,CAAE,IAAM,CAC/E,qBAAO,CAAE,UAAU,CAAE,MAAM,CAAE,OAAO,CAAE,IAAM"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let history = [];
  $$result.css.add(css);
  return `<div class="page svelte-12ipolu"><div class="header svelte-12ipolu"><h1 data-svelte-h="svelte-1b94uzw">Search History</h1> ${history.length > 0 ? `<button class="btn btn-secondary" data-svelte-h="svelte-mqiefm">Clear History</button>` : ``}</div> ${`<div data-svelte-h="svelte-194gxkm">Loading...</div>`} </div>`;
});
export {
  Page as default
};
