[package]
name = "local_store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
core_domain = { path = "../core_domain" }

sqlx.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "db_bench"
harness = false