import { c as create_ssr_component } from "../../../chunks/ssr.js";
import "../../../chunks/api.js";
const css = {
  code: ".page.svelte-gu8eyi{padding:2rem;max-width:1000px}.shares-list.svelte-gu8eyi{display:flex;flex-direction:column;gap:1rem}.share-card.svelte-gu8eyi{padding:1.5rem;display:flex;justify-content:space-between;align-items:center}.actions.svelte-gu8eyi{display:flex;gap:0.5rem}.status.svelte-gu8eyi{font-size:0.875rem;color:var(--gray-600)}.empty.svelte-gu8eyi{text-align:center;padding:3rem}",
  map: `{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script lang=\\"ts\\">import { onMount } from \\"svelte\\";\\nimport { api } from \\"$lib/api/api\\";\\nlet shares = [];\\nlet loading = true;\\nonMount(async () => {\\n  await loadShares();\\n});\\nasync function loadShares() {\\n  try {\\n    shares = await api.getShares();\\n  } catch (error) {\\n    console.error(\\"Failed to load shares:\\", error);\\n  } finally {\\n    loading = false;\\n  }\\n}\\nasync function handleAccept(id) {\\n  try {\\n    await api.acceptShare(id);\\n    shares = shares.map((s) => s.id === id ? { ...s, accepted: true } : s);\\n  } catch (error) {\\n    alert(\\"Failed: \\" + error.message);\\n  }\\n}\\nasync function handleRevoke(id) {\\n  if (!confirm(\\"Revoke this share?\\")) return;\\n  try {\\n    await api.revokeShare(id);\\n    shares = shares.filter((s) => s.id !== id);\\n  } catch (error) {\\n    alert(\\"Failed: \\" + error.message);\\n  }\\n}\\n<\/script>\\n\\n<div class=\\"page\\">\\n\\t<h1>Shared Items</h1>\\n\\n\\t{#if loading}\\n\\t\\t<div>Loading...</div>\\n\\t{:else if shares.length === 0}\\n\\t\\t<div class=\\"empty\\">No shared items</div>\\n\\t{:else}\\n\\t\\t<div class=\\"shares-list\\">\\n\\t\\t\\t{#each shares as share}\\n\\t\\t\\t\\t<div class=\\"share-card card\\">\\n\\t\\t\\t\\t\\t<div>\\n\\t\\t\\t\\t\\t\\t<h3>{share.entity_type} Share</h3>\\n\\t\\t\\t\\t\\t\\t<p>Shared with: {share.shared_with_email}</p>\\n\\t\\t\\t\\t\\t\\t<p>Permissions: {share.permissions.join(', ')}</p>\\n\\t\\t\\t\\t\\t\\t<p class=\\"status\\">{share.accepted ? 'Accepted' : 'Pending'}</p>\\n\\t\\t\\t\\t\\t</div>\\n\\t\\t\\t\\t\\t<div class=\\"actions\\">\\n\\t\\t\\t\\t\\t\\t{#if !share.accepted}\\n\\t\\t\\t\\t\\t\\t\\t<button on:click={() => handleAccept(share.id)} class=\\"btn btn-primary\\">Accept</button>\\n\\t\\t\\t\\t\\t\\t{/if}\\n\\t\\t\\t\\t\\t\\t<button on:click={() => handleRevoke(share.id)} class=\\"btn btn-secondary\\">Revoke</button>\\n\\t\\t\\t\\t\\t</div>\\n\\t\\t\\t\\t</div>\\n\\t\\t\\t{/each}\\n\\t\\t</div>\\n\\t{/if}\\n</div>\\n\\n<style>\\n\\t.page { padding: 2rem; max-width: 1000px; }\\n\\t.shares-list { display: flex; flex-direction: column; gap: 1rem; }\\n\\t.share-card { padding: 1.5rem; display: flex; justify-content: space-between; align-items: center; }\\n\\t.actions { display: flex; gap: 0.5rem; }\\n\\t.status { font-size: 0.875rem; color: var(--gray-600); }\\n\\t.empty { text-align: center; padding: 3rem; }\\n</style>\\n"],"names":[],"mappings":"AAiEC,mBAAM,CAAE,OAAO,CAAE,IAAI,CAAE,SAAS,CAAE,MAAQ,CAC1C,0BAAa,CAAE,OAAO,CAAE,IAAI,CAAE,cAAc,CAAE,MAAM,CAAE,GAAG,CAAE,IAAM,CACjE,yBAAY,CAAE,OAAO,CAAE,MAAM,CAAE,OAAO,CAAE,IAAI,CAAE,eAAe,CAAE,aAAa,CAAE,WAAW,CAAE,MAAQ,CACnG,sBAAS,CAAE,OAAO,CAAE,IAAI,CAAE,GAAG,CAAE,MAAQ,CACvC,qBAAQ,CAAE,SAAS,CAAE,QAAQ,CAAE,KAAK,CAAE,IAAI,UAAU,CAAG,CACvD,oBAAO,CAAE,UAAU,CAAE,MAAM,CAAE,OAAO,CAAE,IAAM"}`
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `<div class="page svelte-gu8eyi"><h1 data-svelte-h="svelte-1a5nump">Shared Items</h1> ${`<div data-svelte-h="svelte-194gxkm">Loading...</div>`} </div>`;
});
export {
  Page as default
};
