pub mod ai_insight;
pub mod ai_interaction;
pub mod attachment;
pub mod audit_log;
pub mod calendar_event;
pub mod communication;
pub mod communication_concept;
pub mod concept;
pub mod concept_matcher;
pub mod conflict_resolution;
pub mod contact;
pub mod group;
pub mod location;
pub mod note;
pub mod pick;
pub mod project;
pub mod relationship;
pub mod resource_acl;
pub mod search_history;
pub mod share;
pub mod sms_history;
pub mod email_history;
pub mod email_triage_session;
pub mod imap_account;
pub mod tag;
pub mod user;

pub use ai_insight::AiInsightRepository;
pub use ai_interaction::AiInteractionRepository;
pub use attachment::AttachmentRepository;
pub use audit_log::AuditLogRepository;
pub use calendar_event::CalendarEventRepository;
pub use communication::CommunicationRepository;
pub use communication_concept::CommunicationConceptRepository;
pub use concept::ConceptRepository;
pub use concept_matcher::{ConceptMatcherRepository, ConceptWithMatchers};
pub use conflict_resolution::ConflictResolutionRepository;
pub use contact::{ContactRepository, MergeStatistics};
pub use group::GroupRepository;
pub use location::LocationRepository;
pub use note::NoteRepository;
pub use pick::PickRepository;
pub use project::ProjectRepository;
pub use relationship::{EntityRelationshipRepository, RelationshipTypeRepository};
pub use resource_acl::ResourceAclRepository;
pub use search_history::SearchHistoryRepository;
pub use share::ShareRepository;
pub use sms_history::{SmsHistoryRepository, SmsMessage, UnlinkedSmsSender};
pub use email_history::{EmailHistoryRepository, EmailMessage, EmailConversation, EmailWithDomains, DomainMembership, OverlapCount, UnlinkedSender};
pub use email_triage_session::{EmailTriageSessionRepository, EmailTriageSession};
pub use imap_account::{ImapAccountRepository, ImapAccount};
pub use tag::TagRepository;
pub use user::UserRepository;
